import type { Edge } from "@xyflow/react";
import type { CodeLine, GraphNode } from "./types";
import { resolvePassiveOutputs, resolvedInputsFor } from "../graph-verify";

// Generates a runnable test file for the current board: one test per passive
// node, asserting that computeNodeOutputs (vitest) / execute_logic_computation
// (pytest) reproduces the values the live engine resolved. These are the same
// hand-written vectors execution-helpers.test.ts / test_passive_parity.py use
// — here they are captured automatically from the user's own graph.

export interface TestFileResult {
  code: string;
  lines: CodeLine[];
  /** shiki grammar for the viewer */
  grammar: string;
  /** "typescript" | "python" — which runner the file targets */
  target: "typescript" | "python";
  /** nodes that could not be turned into a test, with the reason */
  skipped: string[];
}

/** true for values we can serialize into a stable assertion */
const assertable = (v: unknown): boolean => {
  if (v === undefined) return false;
  if (typeof v === "number") return Number.isFinite(v);
  if (typeof v === "function") return false;
  if (Array.isArray(v)) return v.every(assertable);
  if (v !== null && typeof v === "object") return Object.values(v).every(assertable);
  return true;
};

function tsLit(v: unknown): string {
  return JSON.stringify(v) ?? "undefined";
}

function pyLit(v: unknown): string {
  if (v === null || v === undefined) return "None";
  if (typeof v === "boolean") return v ? "True" : "False";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(pyLit).join(", ")}]`;
  if (typeof v === "object") {
    const entries = Object.entries(v as Record<string, unknown>);
    return `{${entries.map(([k, x]) => `${JSON.stringify(k)}: ${pyLit(x)}`).join(", ")}}`;
  }
  return "None";
}

const snake = (s: string) =>
  s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/[^a-zA-Z0-9]+/g, "_").toLowerCase();

/**
 * Builds the test file. `target` follows the code panel's language: "python"
 * emits pytest against the backend engine; every other target emits vitest
 * against the TypeScript engine (both engines are parity-locked, so the
 * vectors are identical either way).
 */
export function generateTestFile(nodes: GraphNode[], edges: Edge[], target: string): TestFileResult {
  const py = target === "python";
  const { values } = resolvePassiveOutputs(nodes, edges);
  const lines: CodeLine[] = [];
  const skipped: string[] = [];
  const push = (text: string, nodeId?: string) => lines.push({ text, nodeId });

  interface Vector {
    node: GraphNode;
    inputs: Record<string, unknown>;
    expected: [string, unknown][];
  }
  const vectors: Vector[] = [];
  for (const node of nodes) {
    if (node.data.inputs.some((i) => i.type === "trigger")) {
      skipped.push(`${node.data.label} — trigger-driven, runs only in a live flow.`);
      continue;
    }
    const out = values.get(node.id);
    if (!out) {
      skipped.push(`${node.data.label} — its value could not be resolved.`);
      continue;
    }
    const expected = Object.entries(out).filter(([, v]) => assertable(v));
    if (expected.length === 0) {
      skipped.push(`${node.data.label} — outputs are dynamic (random/time) or empty.`);
      continue;
    }
    const inputs = resolvedInputsFor(node, nodes, edges, values);
    vectors.push({ node, inputs, expected });
  }

  if (py) {
    push('"""Auto-generated by LogiBoard Build Logic — run with: pytest <this file>');
    push("");
    push("One test per passive node on the board, asserting the Python engine");
    push('reproduces the values the live TypeScript engine computed."""');
    push("from backend.engine import execute_logic_computation");
    for (const { node, inputs, expected } of vectors) {
      push("", node.id);
      push("", node.id);
      push(`def test_${snake(node.data.label)}_${snake(node.id)}():`, node.id);
      push(
        `    out = execute_logic_computation(${pyLit(node.data.type)}, ${pyLit(inputs)}, ${pyLit(node.data.config ?? {})})`,
        node.id
      );
      for (const [port, v] of expected) push(`    assert out[${pyLit(port)}] == ${pyLit(v)}`, node.id);
    }
  } else {
    push("// Auto-generated by LogiBoard Build Logic — run with: npx vitest run <this file>");
    push("// One test per passive node on the board, asserting computeNodeOutputs");
    push("// reproduces the values the live engine resolved.");
    push('import { describe, it, expect } from "vitest";');
    push('import { computeNodeOutputs } from "@/lib/execution-helpers";');
    push("");
    push('describe("Board logic", () => {');
    for (const { node, inputs, expected } of vectors) {
      push(`  it(${tsLit(`${node.data.label} (${node.data.type})`)}, () => {`, node.id);
      push(
        `    const out = computeNodeOutputs(${tsLit(node.data.type)}, ${tsLit(inputs)}, ${tsLit(node.data.config ?? {})});`,
        node.id
      );
      for (const [port, v] of expected) push(`    expect(out[${tsLit(port)}]).toEqual(${tsLit(v)});`, node.id);
      push("  });", node.id);
    }
    push("});");
  }

  if (skipped.length) {
    push("");
    push(py ? "# Not covered:" : "// Not covered:");
    for (const s of skipped) push(`${py ? "#" : "//"}   ${s}`);
  }

  return {
    code: lines.map((l) => l.text).join("\n") + "\n",
    lines,
    grammar: py ? "python" : "typescript",
    target: py ? "python" : "typescript",
    skipped,
  };
}
